name: datalad_binder

channels:
  - default
  - conda-forge

dependencies:
  - python=3.8.*
  - pip
  - pandas
  - numpy
  - seaborn
  - matplotlib
  - nibabel
  - datalad
  - scikit-learn
  - texinfo
